### ISSUE TITLE
Copy pasta (beatmap.ar should be beatmap.hp)

### ISSUE THREAD

**Issue by flesnuk** [Francesco149/koohii#1]
https://github.com/Francesco149/koohii/blob/e7a440c3410e3ffadfda5728c178d5b68f862f5f/Koohii.java#L476-L477

Although you don't use it for anything so doesn't produce any bug. :relieved:

**Comment by Francesco149** [comment]
haha typical copy pasta error, will fix in a sec

**Comment by Francesco149** [comment]
and this would be a major error if HP comes after AR in the .osu file since pp calc has high/low ar bonus and it would overwrite AR
