### ISSUE TITLE
AR=5(default?) when prasing OA period map

### ISSUE THREAD

**Issue by Mother-Ship** [Francesco149/koohii#5]
osu.ppy.sh/b/53554
[Difficulty]
HPDrainRate:8
CircleSize:4
OverallDifficulty:9
SliderMultiplier:2
SliderTickRate:0.5

the maps ranked before 2010.9 ,is OD=AR....
![image](https://user-images.githubusercontent.com/26121316/34430620-de9e795a-eca1-11e7-8d4f-92e15c6965a5.png)

**Comment by Francesco149** [comment]
oops yeah, I forgot about that. 5 is default because iirc it's AR5 when both ar and od are not specified. will fix ASAP, thanks for the report!
